version: "2.1"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-server
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
