debug: true
database:
  host: localhost
  port: 5432
  user: postgres 
  password: postgres
  database: sveta
web:
  host: 127.0.0.1
  port: 8000
bot:
  token:
session:
  key:
admin:
  email: admin@admin.com
  password: admin
sentry:
  dsn:
  env: dev

store: {}
