"""add media

Revision ID: 1d98007c8c62
Revises: 17f50a6afe53
Create Date: 2025-05-14 21:20:41.362374

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d98007c8c62"
down_revision: Union[str, None] = "17f50a6afe53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=256), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("type", sa.Enum("photo", name="mediatype"), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("media")
    # ### end Alembic commands ###
