"""add template model

Revision ID: f889070c5d2a
Revises: 11002909d103
Create Date: 2025-08-03 00:52:22.526090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f889070c5d2a'
down_revision: Union[str, None] = '11002909d103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PAGE', 'PAGINATE', name='templatetype'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('list_template', sa.Text(), nullable=False),
    sa.Column('list_image_path', sa.String(length=256), nullable=True),
    sa.Column('item_template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'model', name='uq_template_type_model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
