"""edit program description

Revision ID: 17f50a6afe53
Revises: 8eb6ae9f141e
Create Date: 2025-05-13 16:48:26.977999

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17f50a6afe53"
down_revision: Union[str, None] = "8eb6ae9f141e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "programs", sa.Column("short_description", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("programs", "short_description")
    # ### end Alembic commands ###
