"""change user

Revision ID: 3dfd67453413
Revises: aedb2441c67f
Create Date: 2025-06-06 18:33:59.430618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3dfd67453413"
down_revision: Union[str, None] = "aedb2441c67f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_name", sa.VARCHAR(length=32), nullable=False))
    op.add_column("users", sa.Column("first_name", sa.VARCHAR(length=64), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.VARCHAR(length=64), nullable=True))
    op.add_column("users", sa.Column("langue_code", sa.VARCHAR(length=10), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(length=20), server_default="user", nullable=True))
    op.alter_column(
        "users",
        "state",
        existing_type=postgresql.ENUM(
            "ACTIVE", "KICKED", "BANNED", name="user_state_enum"
        ),
        type_=sa.String(length=20),
        nullable=True,
        server_default="active",
        postgresql_using="state::text"
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.alter_column('users', 'state', server_default=None)
    op.alter_column(
        "users",
        "state",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM(
            "ACTIVE", "KICKED", "BANNED", name="user_state_enum"
        ),
        nullable=False,
        postgresql_using = "state::user_state_enum"
    )
    op.alter_column('users', 'state', server_default='ACTIVE')
    op.drop_column("users", "role")
    op.drop_column("users", "langue_code")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "user_name")
    # ### end Alembic commands ###
