"""add media title

Revision ID: aedb2441c67f
Revises: cf05d12e3877
Create Date: 2025-06-05 20:58:53.371229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aedb2441c67f"
down_revision: Union[str, None] = "cf05d12e3877"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media", sa.Column("title", sa.String(length=256), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "title")
    # ### end Alembic commands ###
