"""add promo

Revision ID: cf05d12e3877
Revises: 1d98007c8c62
Create Date: 2025-06-04 10:58:39.180380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf05d12e3877"
down_revision: Union[str, None] = "1d98007c8c62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column(
            "old_price", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "new_price", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("promo")
    # ### end Alembic commands ###
